### ISSUE TITLE
Preselect current site in Saved Passwords doesn't work in firefox 49.0.1

### ISSUE THREAD

**Issue by OpenWeb321** [ddawson/Saved-Password-Editor#27] opened 2016-10-10 02:43 UTC
need something like   create username   and random passwords

**Comment by ddawson** [comment] 2016-10-12 03:27
You have described two completely different things in one issue. Please do not do that. If you have two bug reports/requests to make, you need to file them as separate issues. Otherwise, it makes it more difficult to keep track of things. If at some point I were to say, "issue #27 is fixed", what would you make of it? I am going to choose what you described in the title as what this issue is about and ignore the request in the comment for now.

Well, it is still working for me. Can you tell me more about what you are experiencing? Are there sites on which it does work? Please note that it will only work if the initial part of the URL in the current tab's location matches something in your saved passwords. For instance, if the URL starts with "https://www.somesite.com/...", and you have one or more saved passwords with host being "https://www.somesite.com", it works. But if you're currently at "http://www.somesite.com/..." (note the "http" instead of "https") or "https://blah.somesite.com/...", and you don't have one of those in your saved passwords, it won't work.

Is that the problem you see? I could, perhaps, use a relaxed matching rule as a fallback for cases like this. Or is it something else?

**Comment by Maxxxxxx** [comment] 2016-12-02 00:16
Mr Dawson,

I came on because of the header.  I could not click on any of my saved logins and open it to edit, copy. or paste.  I could "show password" and edit it that way, of course.  I often have several logins for the different variations of the same website (shopping/support/whatever) and the bar across the selected login would default to the top selection. 

SPE would also lag in opening and closing. 

With the update of FF 50.0.02 today, _they_ fixed _their_ issues - and the two that I was having with yours.
It's a great program.  I appreciate that it restores so easily.

Thank you.

**Comment by ddawson** [comment] 2016-12-02 01:41
@Maxxxxxx I'm not sure just what you're saying here. However, you do seem to have the misconception I see frequently that SPE provides the Saved Logins window. It does not. Mozilla's code does, and SPE makes a few modifications so that you can add and edit passwords. You don't "open and close" SPE; you open and close Mozilla's interface to the password manager. I do provide that button to access it, though, because the built-in, "normal" way (through the "Security" pane in Options/Preferences) is too obscure for a lot of people, not to mention inconvenient.

Anyway, the cause of my "Edit"/"Clone" not working was a change *they* made that made SPE incompatible. I adapted SPE it to be compatible once again. At least, as much as I could. One or two other issues I know about seem to have been bugs. The issue actual issue of this discussion ("Preselect current site..."; remember, you're supposed to use *separate* discussions for different issues, as this is a bug tracker, not a forum for random conversation) is something I could never reproduce, and @OpenWeb321 has not followed up on my questions for nearly 2 months. So, with that, I am going to close this issue. Please, no one reopen it unless you have usable information about the one issue this discussion is supposed to be about. If you have a different problem, please open a new issue for it. Thank you.

**Closed by ddawson** 2016-12-02 01:41 UTC
